[package]
name = "anchor-bridge-client"
version = "0.1.0"
authors = ["Stan Drozd <stan@nexantic.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0.40"
bridge = {path = "../programs/bridge", features = ["no-idl", "no-entrypoint"]}
clap = "3.0.0-beta.2"
rand = "0.7.3"
shellexpand = "2.1.0"
solana-client = "1.7.0"
solana-program = "*"
solana-sdk = "1.7.0"
solitaire = { path = "../programs/solitaire" }
