[package]
name = "bridge"
version = "0.1.0"
description = "Wormhole bridge core contract"
edition = "2018"

[lib]
crate-type = ["cdylib", "lib"]
name = "bridge"

[features]
no-entrypoint = ["solitaire/no-entrypoint"]
client = ["solitaire-client"]
no-idl = []
cpi = ["no-entrypoint"]
default = []

[dependencies]
borsh = "0.8.1"
byteorder = "1.4.3"
primitive-types = { version = "0.9.0", default-features = false }
sha3 = "0.9.1"
solana-program = "=1.7.0"
solitaire-client = { path = "../../solitaire/client", optional = true}
solitaire = { path = "../../solitaire/program"}

[dev-dependencies]
solana-client = "1.7.0"
solana-sdk = "=1.7.0"
