[package]
name = "solitaire"
version = "0.1.0"
description = "Solana program framework"
edition = "2018"

[lib]
crate-type = ["cdylib", "lib"]
name = "solitaire"

[features]
no-entrypoint = []
no-idl = []
cpi = ["no-entrypoint"]
default = []

[dependencies]
borsh = "0.8.1"
byteorder = "1.4.3"
rocksalt = { path = "../../rocksalt" }
sha3 = "0.9.1"
solana-program = "*"
solana-sdk = "1.7.0"
