[package]
name = "bridge"
version = "0.1.0"
description = "Wormhole bridge core contract"
edition = "2018"

[lib]
crate-type = ["cdylib", "lib"]
name = "bridge"

[features]
no-entrypoint = ["solitaire/no-entrypoint", "solitaire-client"]
no-idl = []
cpi = ["no-entrypoint"]
default = []

[dependencies]
borsh = "0.8.1"
byteorder = "1.4.3"
solitaire = { path = "../solitaire"}
solitaire-client = { path = "../../solitaire-client", optional = true}
sha3 = "0.9.1"
primitive-types = { version = "0.9.0", default-features = false }
solana-program = "=1.7.0"
