---
apiVersion: v1
kind: Service
metadata:
  name: guardian
  labels:
    app: guardian
spec:
  ports:
    - port: 8999
      name: p2p
      protocol: UDP
  clusterIP: None
  selector:
    app: guardian
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: guardian
spec:
  selector:
    matchLabels:
      app: guardian
  serviceName: guardian
  replicas: 5
  updateStrategy:
    # The StatefulSet rolling update strategy is rather dumb, and updates one pod after another.
    # If we want blue-green deployments, we should use a Deployment instead.
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: guardian
    spec:
      terminationGracePeriodSeconds: 0
      volumes:
        - name: key-volume
          configMap:
            # Provide the name of the ConfigMap containing the files you want
            # to add to the container
            name: bridge-keypair
      containers:
        - name: guardiand
          image: guardiand-image
          command:
            - /guardiand
            - -ethRPC
            - ws://eth-devnet:8545
            - -agentRPC
            - localhost:9000
            - -ethConfirmations
            - '3'
            - -unsafeDevMode
#            - -logLevel
#            - debug
          ports:
            - containerPort: 8999
              name: p2p
              protocol: UDP
            - containerPort: 6060
              name: pprof
              protocol: TCP
#          volumeMounts:
#            - name: guardian-data
#              mountPath: /data
        - name: agent
          image: solana-agent
          command:
            - /usr/local/bin/agent
            - 'Bridge1p5gheXUvJ6jGWGeCsgPKgnE3YgdGKRVCMY9o'  # TODO: program address
            - 'solana-devnet'  # host
            - '8899'  # rpc port
            - '8900'  # pubsub/ws port
            - '9000'  # grpc listen port
          ports:
            - containerPort: 9000
              name: grpc
              protocol: TCP
          volumeMounts:
            - name: key-volume
              mountPath: /usr/src/solana
            - name: key-volume
              mountPath: /root/.config/solana
#  volumeClaimTemplates:
#    - metadata:
#        name: guardian-data
#      spec:
#        accessModes: [ "ReadWriteOnce" ]
#        resources:
#          requests:
#            storage: 1Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: bridge-keypair
  namespace: default
data:
  # Key with pubkey 6sbzC1eH4FTujJXWj51eQe25cYvr4xfXbJ1vAj7j2k5J
  id.json: |
    [14,173,153,4,176,224,201,111,32,237,183,185,159,247,22,161,89,84,215,209,212,137,10,92,157,49,29,192,101,164,152,70,87,65,8,174,214,157,175,126,98,90,54,24,100,177,247,77,19,112,47,44,165,109,233,102,14,86,109,29,134,145,132,141]
