---
apiVersion: v1
kind: Service
metadata:
  name: guardian
  labels:
    app: guardian
spec:
  ports:
    - port: 8999
      name: p2p
      protocol: UDP
  clusterIP: None
  selector:
    app: guardian
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: guardian
spec:
  selector:
    matchLabels:
      app: guardian
  serviceName: guardian
  replicas: 5
  updateStrategy:
    # The StatefulSet rolling update strategy is rather dumb, and updates one pod after another.
    # If we want blue-green deployments, we should use a Deployment instead.
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: guardian
    spec:
      terminationGracePeriodSeconds: 0
      volumes:
        # mount shared between containers for runtime state
        - name: bridge-rundir
          emptyDir: {}
      containers:
        - name: guardiand
          image: guardiand-image
          env:
            - name: TERRA_FEE_PAYER
              value: "notice oak worry limit wrap speak medal online prefer cluster roof addict wrist behave treat actual wasp year salad speed social layer crew genius"
          volumeMounts:
            - mountPath: /run/bridge
              name: bridge-rundir
          command:
# Uncomment this to enable in-place debugging using dlv
# (not suitable for regular development since the process will no longer restart on its own)
#
#            - /dlv
#            - --listen=:2345
#            - --accept-multiclient
#            - --headless=true
#            - --api-version=2
#            - --continue=true
#            - exec
            - /guardiand
#            - --
            - bridge
            - --ethRPC
            - ws://eth-devnet:8545
#            - --terra
#            - --terraWS
#            - ws://terra-terrad:26657/websocket
#            - --terraLCD
#            - http://terra-lcd:1317
#            - --terraChainID
#            - localterra
#            - --terraContract
#            - terra174kgn5rtw4kf6f938wm7kwh70h2v4vcfd26jlc
#            - --terraFeePayer
#            - $(TERRA_FEE_PAYER)
            - --agentRPC
            - /run/bridge/agent.sock
            - --ethConfirmations
            - '3'
            - --unsafeDevMode
            - --bridgeKey
            - /tmp/bridge.key
            - --adminSocket
            - /tmp/admin.sock
#            - --logLevel=debug
          securityContext:
            capabilities:
              add:
                # required for syscall.Mlockall
                - IPC_LOCK
          readinessProbe:
            httpGet:
              port: 6060
              path: /readyz
          ports:
            - containerPort: 8999
              name: p2p
              protocol: UDP
            - containerPort: 6060
              name: pprof
              protocol: TCP
        - name: agent
          image: solana-agent
          volumeMounts:
            - mountPath: /run/bridge
              name: bridge-rundir
          command:
            - /usr/local/bin/agent
            - 'Bridge1p5gheXUvJ6jGWGeCsgPKgnE3YgdGKRVCMY9o'
            - 'solana-devnet'  # host
            - '8899'  # rpc port
            - '8900'  # pubsub/ws port
            - '/run/bridge/agent.sock'  # grpc listen socket
          ports:
            - containerPort: 9000
              name: grpc
              protocol: TCP
