---
apiVersion: v1
kind: Service
metadata:
  name: guardian
  labels:
    app: guardian
spec:
  ports:
    - port: 8999
      name: p2p
      protocol: UDP
  clusterIP: None
  selector:
    app: guardian
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: guardian
spec:
  selector:
    matchLabels:
      app: guardian
  serviceName: guardian
  replicas: 5
  updateStrategy:
    # The StatefulSet rolling update strategy is rather dumb, and updates one pod after another.
    # If we want blue-green deployments, we should use a Deployment instead.
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: guardian
    spec:
      terminationGracePeriodSeconds: 0
      volumes:
        - name: key-volume
          configMap:
            name: bridge-keypair
      containers:
        - name: guardiand
          image: guardiand-image
          command:
# Uncomment this to enable in-place debugging using dlv
# (not suitable for regular development since the process will no longer restart on its own)
#
#            - /dlv
#            - --listen=:2345
#            - --accept-multiclient
#            - --headless=true
#            - --api-version=2
#            - --continue=true
#            - exec
            - /guardiand
#            - --
            - bridge
            - --ethRPC
            - ws://eth-devnet:8545
            - --agentRPC
            - localhost:9000
            - --ethConfirmations
            - '3'
            - --unsafeDevMode
#            - --logLevel=debug
          securityContext:
            capabilities:
              add:
                # required for syscall.Mlockall
                - IPC_LOCK
          ports:
            - containerPort: 8999
              name: p2p
              protocol: UDP
            - containerPort: 6060
              name: pprof
              protocol: TCP
        - name: agent
          image: solana-agent
          command:
            - /usr/local/bin/agent
            - 'Bridge1p5gheXUvJ6jGWGeCsgPKgnE3YgdGKRVCMY9o'
            - 'solana-devnet'  # host
            - '8899'  # rpc port
            - '8900'  # pubsub/ws port
            - '9000'  # grpc listen port
          ports:
            - containerPort: 9000
              name: grpc
              protocol: TCP
