---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: terra-lcd
  name: terra-lcd
spec:
  ports:
  - name: lcd
    port: 1317
    protocol: TCP
  selector:
    app: terra-lcd
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: terra-terrad
  name: terra-terrad
spec:
  ports:
  - name: rpc
    port: 26657
    protocol: TCP
  selector:
    app: terra-terrad
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: terra-lcd
  name: terra-lcd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: terra-lcd
  template:
    metadata:
      labels:
        app: terra-lcd
    spec:
      containers:
      - args:
        - terracli
        - rest-server
        - --laddr=tcp://0.0.0.0:1317
        - --node=tcp://terra-terrad:26657
        - --trust-node=true
        - --unsafe-cors
        image: terra-image
        name: terra-lcd
        ports:
        - containerPort: 1317
        readinessProbe:
          tcpSocket:
            port: 1317
      restartPolicy: Always
  serviceName: terra-lcd
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: terra-terrad
  name: terra-terrad
spec:
  replicas: 1
  selector:
    matchLabels:
      app: terra-terrad
  template:
    metadata:
      labels:
        app: terra-terrad
    spec:
      containers:
      - args:
        - terrad
        - start
        image: terra-image
        name: terra-terrad
        ports:
        - containerPort: 26657
        readinessProbe:
          httpGet:
            port: 26657
        resources: {}
      - name: terra-contracts
        image: terra-contracts
      restartPolicy: Always
  serviceName: terra-terrad
